### ISSUE TITLE
Avoid to ship the package with a version of React

### ISSUE THREAD

**Issue by samouss** [Swizec/useDimensions#2]
The package is shipped with a hard dependencies on `react@^16.8.4"`. Which means that if somone install the hook on a React application that have a fixed/different requirement for the version it might end up with two different versions of React in the same App. It appears that the hooks require to [have only one copy of React](https://reactjs.org/warnings/invalid-hook-call-warning.html) in the same App, otherwise it throws an error. You should move the hard dependencies to a [`peerDependencies`](https://docs.npmjs.com/files/package.json#peerdependencies), it should solve the issue.

> https://codesandbox.io/s/7y952kv541

**Comment by Swizec** [comment]
Good catch! Just fixed, releasing in a bit.
