### ISSUE TITLE
Dimensions are not updated when the size have been changed dinamically

### ISSUE THREAD

**Issue by seleckis** [Swizec/useDimensions#26]
I have a flexbox layout which child components changes their size on keypress. But the hook does not return updated size. Tried useEffect and useLayoutEffect without luck. Please check an example: https://codesandbox.io/s/laughing-dubinsky-tzidt?fontsize=14&hidenavigation=1&theme=dark

**Comment by seleckis** [comment]
Switched to another solution

**Comment by gabtorr** [comment]
> Switched to another solution

Hi, im facing the same issue, is there another package that supports this kind of problem? or you developed one by yourself? thanks!
