### ISSUE TITLE
Using useDimensions to make autosized input boxes

### ISSUE THREAD

**Issue by junaid33** [Swizec/useDimensions#4]
I was trying to use this package to create an autosized input that adapts to the text inside. I got it to work, but I have to render the text that the width comes from like such:

`<>
<text ref={stepRef}>The title</text>
<input value="The title" style={{ width: stepSize.width }} />
</>`

Is there anyway to hide the text that we are getting the width from? Or perhaps a cleaner way to do this?

**Comment by Swizec** [comment]
Hey @junaid33 sorry I just saw this now.

Have you resolved the problem yet or maybe you can provide a codesandbox so that I can understand your context better?
